### ISSUE TITLE
Support file inputs 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cupid#71]
#### Reason/Context
Triggered by https://github.com/asyncapi/cupid/issues/67#issuecomment-968961039, as we currently have no way to pass options to the parser that Cupid uses. Meaning everyone needs to pre-parse their documents beforehand for references to be accurately dereferenced.

We can remove such needs by supporting file inputs (or a way to pass options to the parser 🧐).

**Comment by derberg** [comment]
The reason for not having such functionality here (or why it was not added) is because this library should eventually be integrated into CLI and Studio where these things are done already. Less logic, better, until we see adoption outside AsyncAPI tools

**Comment by jonaslagoni** [comment]
> The reason for not having such functionality here (or why it was not added) is because this library should eventually be integrated into CLI and Studio where these things are done already

Right, but when you need to natively integrate this library into your own tools, it becomes a missing feature. Especially if I do not care about CLI or Studio 😄

**Comment by derberg** [comment]
> Especially if I do not care about CLI or Studio 😄

Do you mean you or as an imaginary user?
Why would you use the library directly for social media example, or any other instead of just calling CLI?

> but when you need to natively integrate this library into your own tools, it becomes a missing feature

well, yes and no. How do you know, do you have a use case 😄 ? Cupid was developed as a library for CLI and Studio, but also developed in a separate repo and released separately in case someone would like to integrate it into their tools. 

so supporting file input is cool, but why would I do it just because I think it could be useful :) What is the point of adding features that we and nobody else needs 😄 

Do you know what I mean? otherwise, we will add file input, then of course URL input as this would be nice too?

**Comment by jonaslagoni** [comment]
>Do you mean you or as an imaginary user?
>Why would you use the library directly for social media example, or any other instead of just calling CLI?

I mean, at the moment, I have this problem, because CLI is not integrated yes.

So you could say this feature request would go away with that feature implemented.

> well, yes and no. How do you know, do you have a use case 😄 ? 

Yes, because I have no other choice than to implement it myself 😄

**Comment by derberg** [comment]
then easier would be if you join review here https://github.com/asyncapi/cli/pull/143 and help by doing manual testing dev experience:

```bash
git clone https://github.com/asyncapi/cli
gh pr checkout 143 #assuming you have a GH CLI
npm install
npm run build #ts thingy
npm install ./ -g #get asyncapi installed globally, but basically get a symlink to clone 
asyncapi relation test/examples/flightService/monitor.yaml test/examples/flightService/notifier.yaml test/examples/flightService/subscriber.yaml
```

😁

**Comment by jonaslagoni** [comment]
Just had another use-case for Cupid the other day where I integrated it into a website, so the feature request stands.
